### ISSUE TITLE
"Purge Caches" option shouldn't be in "view"

### ISSUE THREAD

**Issue by Miepee** [cristian64/mkdd-extender#17]
When I read "purge cache" I don't think in any way of how the view would change. I'd recommend moving that option into the "Options" page, then it could also have a little tooltip there of what kind of caches are deleted.

**Comment by cristian64** [comment]
The **Options** dialog is currently reserved for options that alter the resulting ISO.

The **Purge Cache** action is used to clear the cached data that has ever been previewed on the right-hand side pane. It's under **View** menu as that's where it lives in Dolphin too. I guess it could be renamed to **Purge Preview Cache** to be more specific (although I remember being vague _intentionally_, so that the action could be reuse for flushing other things in the future).

**Comment by Miepee** [comment]
Ah, I see. Yeah, a rename of that would be a bit better then.
